apiVersion: v1
kind: ConfigMap
metadata:
  name: vdlg-notification-config
  namespace: vdlg
data:
  ENV: "dev"
  PORT: "8080"
  CUSTOMER_URL: "http://vdlg-customer.vdlg.svc.cluster.local:8080"
  OUTPUT_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/000047597454/NotificationOutputQueue" 
  AWS_REGION: "us-east-1"
  SMTP_USER: "trembaotecnologiasender@gmail.com"