apiVersion: v1
kind: Secret
metadata:
  name: vdlg-notification-secret
  namespace: vdlg
  labels:
    app: vdlg-notification
    environment: "dev"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""
  SMTP_PASS: ""
  